import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ArtistResponse } from "./api/artists/[artistId]/route";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //   const artistsResponse = await fetch("http://localhost:3000/api/artists");
  //   const artists: ArtistsResponse = await artistsResponse.json();
  const artistsResponse = await fetch("http://localhost:3000/api/artists/2");

  const artist: ArtistResponse = await artistsResponse.json();

  if (artist.success) {
    const name = artist.data.name;
    console.log(name);
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
